name: sphinx

on:
  push:
    branches:
    - main

jobs:
  release:
    name: Build Sphinx
    runs-on: ubuntu-latest
    steps:
    - name: Credentials
      run: |
        git init
        git config --global user.email "emanuele.guidotti@unine.ch"
        git config --global user.name "Emanuele Guidotti"
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd docs
        sudo apt install pandoc
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build sphinx documentation
      run: |
        cd docs
        make html
    - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages